name: Lint Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  markdownLint:
    name: "Lint Markdown Files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: articulate/actions-markdownlint@v1
  yamlLint:
    name: "Lint Yaml Files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3
